### ISSUE TITLE
Query methods ancestor, preceding-sibling, following-sibling

### ISSUE THREAD

**Issue by erk-dik** [LionWeb-io/lionweb-csharp#21]
Hi @enikao, @dslmeinte, @JojoEffect,  

As far as I am concerned, the current implementation lacks the following methods, as explained below:

Ancestor: queries the ancestor nodes filtered by a type, something like:
```
public static T? Ancestor<T>(this INode node, bool includeSelf = false) where T : INode =>
    node.Ancestors(includeSelf)
        .OfType<T>()
        .FirstOrDefault();
```
PrecedingSibling  (PrevSiblings) / FollowingSibling  (NextSiblings): queries previous/next siblings of a node, with an optional parameter that specifies whether to include the current node.

**Comment by enikao** [comment]
The question is whether we should implement this in lionweb-csharp or a downstream project. Do you think it's generally useful?

**Comment by enikao** [comment]
Compare to XPath axes: https://www.w3.org/TR/1999/REC-xpath-19991116/#axes
