### ISSUE TITLE
Make all generated public interfaces, classes and structs *partial*

### ISSUE THREAD

**Issue by JojoEffect** [LionWeb-io/lionweb-csharp#31]
To be able to more easily extend the generated concepts and interfaces and additionally to easily add the non-generatable parts of the languages (e.g. the behaviours) it would be helpful to have the generated types represented as `public partial class|interface|struct XYZ` types.

**Comment by JojoEffect** [comment]
@enikao I would expect this to be a small extension to the generator - Do you think it is possible to have this implemented in the very near future?

**Comment by JojoEffect** [comment]
> Do we generate `struct`s anywhere?

Not as far as I know - just wanted make the requirement more general. I'm fully satisfied if non-existing structs are not made partial 😬

**Comment by enikao** [comment]
Implemented in #32
