### ISSUE TITLE
Shall we include Utf8JsonAsyncStreamReader until new package has been released?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/lionweb-csharp#34]
For #26, we depend on https://github.com/gragra33/Utf8JsonAsyncStreamReader/issues/3.

Do we want to include the sources ourselves in the meantime, so we can merge the PR?
License of Utf8JsonAsyncStreamReader is MIT, so we should be ok.

**Comment by enikao** [comment]
@dslmeinte, @JojoEffect  What do you think?

**Comment by dslmeinte** [comment]
I think a PR on a true fork of the original lib would be cleanest as long as we can make some sort of release from that as well. Once the fix has been merged back, we can switch over to the original lib again.

**Comment by JojoEffect** [comment]
I agree with what @dslmeinte said.

Another (obvious) Option: use a different lib if there is one 😬

**Comment by gragra33** [comment]
@JojoEffect @dslmeinte @enikao Latest version is published. Also supports .Net 8.0. .Net 9.0 support is approx a week once released.

**Comment by enikao** [comment]
Obsolete because https://github.com/gragra33/Utf8JsonAsyncStreamReader/issues/3 has been implemented
